config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations' }
  root to: 'plans#index'

  resources :plans do
    resources :features, only: %i[index create new]
    resource :subscriptions, only: %i[create]
    resource :charges, only: %i[create new]
  end
  resource :subscriptions, only: %i[show]

  resources :features, only: %i[update destroy edit]
  resources :usages

  get 'usages/user/:id/plans', to: 'usages#plan'
  get 'usages/user/:id/features', to: 'usages#features'
  get 'transactions', to: 'transactions#abc'
end

app/models/plan.rb
# frozen_string_literal: true

class Plan < ApplicationRecord
  has_many :features, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :monthly_fee, numericality: { only_integer: true }
end

app/controllers/plans_controller.rb
# frozen_string_literal: true

class PlansController < ApplicationController
  before_action :authenticate_user!, :auth
  before_action :set_plan, only: %i[edit update destroy]

  def index
    @plans = Plan.where.not(id: Subscription.current_users(current_user.id).pluck(:plan_id))
    @plans.preload(:features)
  end

  def new
    @plan = Plan.new
  end

  def destroy
    byebug
    if @plan.destroyed?
      byebug
      flash[:notice] ='sucessfully deleted the Plan'
      redirect_to root_path
    else
      byebug
      redirect_to root_path
    end

  end

  def create
    @plan = Plan.new(plan_params)

    if @plan.valid? && @plan.save

      redirect_to root_path
    else

      flash[:errors] = @plan.errors.full_messages
      render :new
    end
  end

  def update
    if @plan.update(plan_params)
      flash[:notice] = 'Plan Updated Successfully'
      redirect_to root_path
    else
      flash.now[:notice] = 'could not update the plan'
      render :edit
    end
  end

  private

  def plan_params
    params.require(:plan).permit(:name, :monthly_fee)
  end

  def auth
    authorize Plan
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end

end

app/helpers/plans_helper.rb
# frozen_string_literal: true

module PlansHelper
  def admin?
    current_user.admin?
  end
end

app/views/plans/_form.html.erb
<%= form_with model:plan do |f|%>

  <% if plan.errors.any? %>
    <ul>

    <% plan.errors.messages.each do |message| %>
      <li><%= message %></li>
    <% end %> 
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name , required: true%>


  <%= f.label :monthly_fee %>
  <%= f.text_field :monthly_fee, required: true%>

  <div>
    <%= f.submit %>
  </div>
  <% end %>

app/views/plans/_plan.html.erb
                <%= link_to plan_features_path(plan), :class=>'features'  do%>


                <div class="col-md-3 col-sm-6 mt-4">
                    <div class="pricingTable blue">
                        <div class="pricingTable-header">
                            <span class="heading">
                                <h3><%= plan.name%></h3>
                                <span class="subtitle">Lorem ipsum dolor sit</span>
                            </span>
                            <span class="price-value">$<%=plan.monthly_fee%> <span>monthly</span></span>
                        </div>
                        <div class="pricingContent">
                            <ul>
                                <%= render plan.features %>
                            </ul>
                        </div><!-- /  CONTENT BOX-->
                        <div class="pricingTable-sign-up">
                        <%#if admin?%>
                            <%#= link_to 'Add Feature', new_plan_feature_path(plan), method: :get ,:class => "btn btn-block"%>
                        <%# else %>
                            <%= link_to 'Subscribe', plan_subscriptions_path(plan,plan.monthly_fee), method: :post, remote:true ,:class => "btn btn-block"%>
                        <% #end %>
                        </div><!-- BUTTON BOX-->
                    </div>
                </div>
            <% end %>

app/views/plans/edit.html.erb
<h1> IN EDIT PAGE</h1>

<%= render "form" , plan:@plan%>

app/views/plans/index.html.erb
 <div class="demo">
    <div class="container">
      <div class = "row">
        <%= render @plans%>
      </div>
    </div>
</div>

app/views/plans/new.html.erb
<h1>Add a new plan</h1>
<%= form_with model:Plan.new do |f|%>

  <%= f.label :name %>
  <%= f.text_field :name%>


  <%= f.label :monthly_fee %>
  <%= f.text_field :monthly_fee%>
  <%= f.file_field :images , multiple: false%>

  <div>
    <%= f.submit %>
  </div>
  <% end %>