config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations' }
  root to: 'plans#index'

  resources :plans do
    resources :features, only: %i[index create new]
    resource :subscriptions, only: %i[create]
    resource :charges, only: %i[create new]
  end
  resource :subscriptions, only: %i[show]

  resources :features, only: %i[update destroy edit]
  resources :usages

  get 'usages/user/:id/plans', to: 'usages#plan'
  get 'usages/user/:id/features', to: 'usages#features'
  get 'transactions', to: 'transactions#abc'
end

app/models/feature.rb
# frozen_string_literal: true

class Feature < ApplicationRecord
  belongs_to :plan

  has_many :usages, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :unit_price, numericality: { only_integer: true }
  validates :max_unit_limit, numericality: { only_integer: true }
  validates :code, uniqueness: true, numericality: { only_integer: true }
end

app/controllers/features_controller.rb
# frozen_string_literal: true

class FeaturesController < ApplicationController
  before_action :auth
  before_action :set_feature, only: %i[edit destroy update]
  before_action :set_plan, only: %i[index new create]

  def index
    @feature = Feature.where(plan_id: params[:plan_id])
  end

  def new
    @features = @plan.features.build
  end

  def create
    @features = @plan.features.new(feature_params)
    if @features.save
      flash[:notice] = 'Feature Created Successfully'

      redirect_to plan_features_url
    else
      flash.now[:notice] = @features.errors.messages
      render :new
    end
  end

  def update
    if @feature.update(feature_params)

      flash[:notice] = 'Feature Updated Successfully'
      redirect_to plan_features_path(params[:id])
    else
      flash[:alert] = 'Feature could not be update'
      render :edit
    end
  end

  def destroy
    redirect_to [params[:plan_id], Plan] if @feature.destroy
  end

  def auth
    authorize Feature
  end

  private

  def set_feature
    @feature = Feature.find(params[:id])
  end

  def set_plan
    @plan = Plan.find(params[:plan_id])
  end

  def feature_params
    params.require(:feature).permit(:code, :description, :name, :unit_price, :max_unit_limit)
  end
end

app/helpers/features_helper.rb
# frozen_string_literal: true

module FeaturesHelper
end

app/views/features/_feature.html.erb
    <%# <li>50GB Disk Space <i class="fa fa-check"></i></li>
    <li>50 Email Accounts <i class="fa fa-check"></i></li>
    <li>50GB Monthly Bandwidth <i class="fa fa-check"></i></li>
    <li>10 subdomains <i class="fa fa-check"></i></li>
    <li>15 Domains <i class="fa fa-times"></i></li> %>

    <li><%= feature.name %> <i class="fa fa-check"></i></li>

app/views/features/_form.html.erb
<%= form_with model:feature  do |form|%>
      <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @features.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
    <div class="field form-group ">
    <%= form.label :code %><br>
    <%= form.text_field :code %>
    <% @features.errors.full_messages_for(:code).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div class="field form-group ">
    <%= form.label :unit_price %><br>
    <%= form.text_field :unit_price %>
    <% @features.errors.full_messages_for(:unit_price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :max_unit_limit %><br>
    <%= form.text_area :max_unit_limit %><br>
    <% @features.errors.full_messages_for(:max_unit_limit).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/features/edit.html.erb
<%# <%= render 'form', feature: @feature %> %>
<p>in eidt route</p>

app/views/features/index.html.erb
<%= link_to 'Edit plan',edit_plan_path(@plan),:class=>"btn btn-primary"%>

          <%= link_to @plan, method: :delete, :class=>"btn btn-danger",
          data: {confirm: "Are you sure you want to delete this Plan?"},
          remote:true do %>Delete Plan
          <% end %>
<ul>

<table class="table"> 
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Limit</th>
      <%if policy(@feature).edit?%>
      <th scope="col">Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% @feature.each do |f|%>
    <tr>
      <td><%= f.name%></td>
      <td><%= f.unit_price%></td>
      <td><%= f.max_unit_limit%></td>
      <%if policy(@feature).edit?%>
      <td><%= link_to 'Edit', edit_feature_path(f) ,:class=>"btn btn-primary"%>
          <%= link_to f, method: :delete, :class=>"btn btn-danger",
          data: {confirm: "Are you sure you want to delete this Feature?"},
          remote:true do %>
          Delete
          <% end %>
      </td>
      <% end %>
    </tr>
<% end %>
  </tbody>
</table>

app/views/features/new.html.erb
<h1>Add a new plan</h1>
<%# <%= form_with model:[@plan, @plan.features.build]  do |form|%>
  <%= render 'form', feature:[@plan, @plan.features.build] %>
  <%# <% end %>