config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations' }
  root to: 'plans#index'

  resources :plans do
    resources :features, only: %i[index create new]
    resource :subscriptions, only: %i[create]
    resource :charges, only: %i[create new]
  end
  resource :subscriptions, only: %i[show]

  resources :features, only: %i[update destroy edit]
  resources :usages

  get 'usages/user/:id/plans', to: 'usages#plan'
  get 'usages/user/:id/features', to: 'usages#features'
  get 'transactions', to: 'transactions#abc'
end

app/controllers/charges_controller.rb
# frozen_string_literal: true

class ChargesController < ApplicationController
  before_action :authenticate_user!
  before_action :subscription_params, :load_plans
  def create
    stripe = StripeService.new(@subscription_params)
    stripe.pay(params[:stripeEmail], params[:stripeToken], @amount.to_i)

    redirect_to root_path
  end
end

  private

def subscription_params
  @subscription_params = { plan_id: params[:plan_id], user_id: current_user.id }
end

# def auth
#   authorize Charge
# end

def load_plans
  plan = Plan.find(params[:plan_id])
  @amount = plan.monthly_fee
end

app/helpers/charges_helper.rb
# frozen_string_literal: true

module ChargesHelper
end

app/views/charges/new.html.erb
  <%= form_tag plan_charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= @amount %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount=@amount
          data-locale="auto"></script>
<% end %>