config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations' }
  root to: 'plans#index'

  resources :plans do
    resources :features, only: %i[index create new]
    resource :subscriptions, only: %i[create]
    resource :charges, only: %i[create new]
  end
  resource :subscriptions, only: %i[show]

  resources :features, only: %i[update destroy edit]
  resources :usages

  get 'usages/user/:id/plans', to: 'usages#plan'
  get 'usages/user/:id/features', to: 'usages#features'
  get 'transactions', to: 'transactions#abc'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #e3f2fd;">
  <%= image_tag(current_user.image.variant(resize: '100x100')) if current_user.image.attached? %>
  <%= link_to 'Payment System' ,root_path,:class=>"navbar-brand"  %>
  <%# <a class="navbar-brand" href="#">Pay  ment System</a> %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">


    <% if admin? %>
      <li class="nav-item ">
        <%= link_to "ADD New Plan", new_plan_path ,:class=>"nav-link"%> <span class="sr-only">(current)</span>
      </li>
      <li class="nav-item">
        <%= link_to "New Usage", new_usage_path ,:class=>"nav-link"%> <span class="sr-only">(current)</span>
      </li>

      <li class="nav-item">

        <%= link_to "New Invitation", new_user_invitation_path ,:class=>"nav-link"%> <span class="sr-only">(current)</span>
      </li>
      <li class="nav-item">
        <%= link_to "Show Usages", usages_path ,:class=>"nav-link"%> <span class="sr-only">(current)</span>
      </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_url ,:class=>"nav-link", method: :delete%> <span class="sr-only">(current)</span>

      </li>
      <li class="nav-item">
      <%= link_to "Edit Profile", edit_user_registration_path ,:class=>"nav-link"%> <span class="sr-only">(current)</span>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

        <title>PaymentSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  </head>

  <body>
  <% if user_signed_in? %>
    <%= render "layouts/navbar" %>
  <%end %>
    <div class = "m-5 p-5">
      <%= yield %>

      <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    </div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </body>
</html>